version: '3.8'
services:
  node1:
    image: farooqtahsin/node
    container_name: node-1
    ports:
      - "8081:8080"
    environment:
      - DATABASE_FOLDER_PATH=/app/DataBase
      - NODE_NAME=node1
      - AFFINITY=http://affinity-node-1:8080/api
    volumes:
      - node1-storage:/app/DataBase

  node2:
    image: farooqtahsin/node
    container_name: node-2
    ports:
      - "8082:8080"
    environment:
      - DATABASE_FOLDER_PATH=/app/DataBase
      - NODE_NAME=node2
      - AFFINITY=http://affinity-node-1:8080/api
    volumes:
      - node2-storage:/app/DataBase

  node3:
    image: farooqtahsin/node
    container_name: node-3
    ports:
      - "8083:8080"
    environment:
      - DATABASE_FOLDER_PATH=/app/DataBase
      - NODE_NAME=node3
      - AFFINITY=http://affinity-node-2:8080/api
    volumes:
      - node3-storage:/app/DataBase

  node4:
    image: farooqtahsin/node
    container_name: node-4
    ports:
      - "8084:8080"
    environment:
      - DATABASE_FOLDER_PATH=/app/DataBase
      - NODE_NAME=node4
      - AFFINITY=http://affinity-node-2:8080/api
    volumes:
      - node4-storage:/app/DataBase

  affinity-node-1:
    image: farooqtahsin/affinity-node
    container_name: affinity-node-1
    ports:
      - "8085:8080"
    environment:
      - DATABASE_FOLDER_PATH=/app/DataBase
    volumes:
      - affinity-node1-storage:/app/DataBase

  affinity-node-2:
    image: farooqtahsin/affinity-node
    container_name: affinity-node-2
    ports:
      - "8086:8080"
    environment:
      - DATABASE_FOLDER_PATH=/app/DataBase
    volumes:
      - affinity-node2-storage:/app/DataBase

  bootstrapping-node:
    image: farooqtahsin/bootstrapping-node
    container_name: bootstrapping-node
    ports:
      - "8087:8080"
    environment:
      - DATABASE_FOLDER_PATH=/app/DataBase
    volumes:
      - bootstrapping-node-storage:/app/DataBase

volumes:
  bootstrapping-node-storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./bootstrapping-node/DataBase
  affinity-node1-storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./affinity-node/DataBase/affinity-node-1
  affinity-node2-storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./affinity-node/DataBase/affinity-node-2
  node1-storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node/DataBase/node1
  node2-storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node/DataBase/node2
  node3-storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node/DataBase/node3
  node4-storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node/DataBase/node4
