version: '3.8'
services:
  node1:
    build: ./node
    container_name: node-1
    ports:
      - "8081:8080"
    environment:
      - DATABASE_FOLDER_PATH=/app/DataBase
    volumes:
      - node1-storage:/app/DataBase

  node2:
    build: ./node
    container_name: node-2
    ports:
      - "8082:8080"
    environment:
      - DATABASE_FOLDER_PATH=/app/DataBase
    volumes:
      - node2-storage:/app/DataBase

  node3:
    build: ./node
    container_name: node-3
    ports:
      - "8083:8080"
    environment:
      - DATABASE_FOLDER_PATH=/app/DataBase
    volumes:
      - node3-storage:/app/DataBase

  affinity-node:
    build: ./affinity-node
    container_name: affinity-node
    ports:
      - "8084:8080"
    environment:
      - DATABASE_FOLDER_PATH=/app/DataBase
    volumes:
      - affinity-node-storage:/app/DataBase

  bootstrapping-node:
    build: ./bootstrapping-node
    container_name: bootstrapping-node
    ports:
      - "8085:8080"
    environment:
      - DATABASE_FOLDER_PATH=/app/DataBase
    volumes:
      - bootstrapping-node-storage:/app/DataBase

volumes:
  bootstrapping-node-storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./bootstrapping-node/DataBase
  affinity-node-storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./affinity-node/DataBase
  node1-storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node/DataBase/node1
  node2-storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node/DataBase/node2
  node3-storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node/DataBase/node3
