version: '3.8'
services:
  node1:
    build: ./node
    container_name: node-1
    ports:
      - "8081:8080"
    environment:
      - DATABASE_FOLDER_PATH=/app/DataBase
    volumes:
      - db-storage:/app/DataBase

  node2:
    build: ./node
    container_name: node-2
    ports:
      - "8082:8080"
    environment:
      - DATABASE_FOLDER_PATH=/app/DataBase
    volumes:
      - db-storage:/app/DataBase

  node3:
    build: ./node
    container_name: node-3
    ports:
      - "8083:8080"
    environment:
      - DATABASE_FOLDER_PATH=/app/DataBase
    volumes:
      - db-storage:/app/DataBase


  affinity-node:
    build: ./affinity-node
    container_name: affinity-node
    ports:
      - "8084:8080"
    environment:
      - DATABASE_FOLDER_PATH=/app/DataBase
    volumes:
      - db-storage:/app/DataBase

volumes:
  db-storage:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./affinity-node/src/main/java/com/atypon/nosql/affinitynode/DataBase