name: CI/CD pipeline for capston project
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Build worker node & push to docker hub
      run: |
        cd node
        mvn clean install
        docker build -t docker.io/farooqtahsin/node -f Dockerfile .
        docker push docker.io/farooqtahsin/node
        cd ..
        
    - name: Build affinity node & push to docker hub
      run: |
        cd affinity-node
        mvn clean install
        docker build -t docker.io/farooqtahsin/affinity-node -f Dockerfile .
        docker push docker.io/farooqtahsin/affinity-node
        cd ..
        
    - name: Build bootstrapping node & push to docker hub
      run: |
        cd bootstrapping-node
        mvn clean install
        docker build -t docker.io/farooqtahsin/bootstrapping-node -f Dockerfile .
        docker push docker.io/farooqtahsin/bootstrapping-node

